general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
    ignore_dbus_inhibit = false
}

listener {
    timeout = 150                               # 2.5 minutes
    on-timeout = brightnessctl -s set 10        # Dim screen backlight
    on-resume = brightnessctl -r                # Restore backlight
}

listener {
    timeout = 300                               # 5 minutes
    on-timeout = loginctl lock-session          # Lock screen
}

listener {
    timeout = 330                               # 5.5 minutes
    on-timeout = hyprctl dispatch dpms off      # Turn off monitors
    on-resume = hyprctl dispatch dpms on        # Turn on monitors on activity
}
